apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditseverity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditSeverity
  template:
    metadata:
      labels:
        app: AuditSeverity
    spec:
      containers:
      - name: auditseverityrepos
        image: samplecr.azurecr.io/auditseverityrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: auditseverity
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditSeverity
